name: Guillaume Royer
description: Blog about web development.
url: https://blog.guilro.com
timezone: Europe/Paris
sass:
  sass_dir: bower_components/
kramdown:
   input: GFM
   hard_wrap: false
gems:
  - jekyll-seo-tag
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
exclude: [bower_components, bower.json]
